server:
  port: 8086

spring:
  application:
    name: wallet-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/eventone
      auto-index-creation: true
  redis:
    host: localhost
    port: 6380
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

wallet:
  challenge:
    ttl-seconds: 300
    chain-id: 8453 # Base
    chain-name: BASE
