spring:
  application:
    name: checkin-service
server:
  port: 8085 # Random port for tests and default startup
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
