server:
  port: 8086

spring:
  application:
    name: realtime-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: realtime-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eventone:
  socketio:
    port: 9090
    host: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
