server:
  port: 8084

spring:
  application:
    name: wallet-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/eventone
      auto-index-creation: true
  redis:
    host: localhost
    port: 8084
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

wallet:
  challenge:
    ttl-seconds: 300
    chain-id: 8453 # Base
    chain-name: BASE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
