server:
  port: 8090

spring:
  application:
    name: ai-service
  data:
    redis:
      host: localhost
      port: 8090

eventone:
  services:
    event: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
