import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Lilita_One } from "next/font/google";
import { Erica_One } from "next/font/google";
import SmoothScroll from "@/components/SmoothScroll";
import Transition from "@/components/atoms/Transition";
import { TransitionProvider } from "@/contexts/TransitionContext";
import LoadingSequence from "@/components/organisms/LoadingSequence";
import LayoutRouteWatcher from "@/components/organisms/LayoutRouteWatcher";
import CustomScrollbar from "@/components/atoms/CustomScrollbar";
import "./global.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lilitaOne = Lilita_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-lilita-one",
});

const ericaOne = Erica_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-erica-one",
});

export const metadata: Metadata = {
  title: "Event App GenZ",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
  manifest: "/site.webmanifest",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lilitaOne.variable} ${ericaOne.variable} antialiased overflow-x-hidden`}
      >
        <LoadingSequence />
        <CustomScrollbar />
        <TransitionProvider>
          <LayoutRouteWatcher>
            <SmoothScroll />
            <Transition>
              {children}
            </Transition>
          </LayoutRouteWatcher>
        </TransitionProvider>
      </body>
    </html>
  );
}
